#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:56057/ms_payment
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  liquibase:
#    change-log: classpath:liquibase/changelog-master.yml
#
#  client:
#    ms-country:
#       endpoint: http://localhost:8081



server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_payment
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

management:
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always

client:
  ms-country:
    endpoint: http://localhost:8081

resilience4j.circuit-breaker:
  instances:
    countryService:
      register-health-indicator: true
      failure-rate-threshold: 50
      minimum-number-of-calls: 5
      wait-duration-in-open-state: 30s
      automatic-transition-from-open-to-half-open-enabled: true
      permitted-number-of-calls-in-half-open-state: 2
      sliding-window-size: 4
      sliding-window-type: COUNT_BASED
